chore: add typos job to GitHub CI workflow
joseluisq/static-web-server pull request #141
Opened 2022-09-17 13:09 UTC by kianmeng

See:
- https://github.com/crate-ci/typos
- https://github.com/joseluisq/static-web-server/pull/140#issuecomment-1249272510

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

2022-09-17 19:41 UTC, joseluisq requested changes
After the address the feedback we can merge this.

2022-09-17 19:41 UTC, joseluisq commented on typos.toml
> +prefered = "prefered"
Can we move the `typos.toml` to `.github/workflows/config/typos.toml`.

2022-09-17 19:41 UTC, joseluisq commented on .github/workflows/devel.yml
> +        config: ./typos.toml
After moving `typos.toml` file then of course, we have to update this path.

2022-09-18 16:13 UTC, joseluisq approved these changes
Thanks 👍

2022-09-18 16:13 UTC, merged

2022-09-19 10:49 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: