feat: Prometheus metrics endpoint at /metrics
joseluisq/static-web-server pull request #296
Opened 2023-12-26 05:44 UTC by pl4nty

## Description

Implements an optional Prometheus metrics endpoint at `/metrics`. Currently provides [Tokio RuntimeMetrics](https://docs.rs/tokio/latest/tokio/runtime/struct.RuntimeMetrics.html) via [tokio-metrics-collector](https://github.com/Hanaasagi/tokio-metrics-collector), requiring `tokio_unstable`. I tried implementing task metrics for the HTTPS redirect Tokio tasks, but no metrics were produced.

## Related Issue

Fixes #125

## Motivation and Context

Many cloud-native environments (eg Kubernetes) use the Prometheus metrics format for performance monitoring.

## How Has This Been Tested?

`cargo run`, `make test`, and CI on forked master branch.

2024-01-03 23:13 UTC, joseluisq commented
@pl4nty some comments after a quick look.

> Build fails on Windows platforms, possibly due to missing RuntimeMetrics.

Yes, it fails for other targets as well. I think we can enable the SWS metrics feature only for Linux as a first stage.

About the Tokio runtime metrics.
It's fine to provide only _runtime_ metrics for now. So let's focus on that.
I also believe that since the Tokio runtime metrics feature is unstable, we could introduce the SWS as experimental like `--experimental-metrics` once we make it work to be usable.
The reason is that we don't know when Tokio runtime metrics will be stable, so until then we have to signal users the intention via an experimental flag.

I didn't test the PR yet but I will give it a detailed look in the next few days. But for now, the initialization in `server.rs` looks ok.
Please feel free to continue updating the draft or ping me if necessary.

2024-01-03 23:19 UTC, joseluisq commented
Also, it would be great to add a few tests and share some output of how it looks like as well as how it goes when integrating with a server that consumes the metrics endpoint.

2024-01-04 12:41 UTC, pl4nty commented
this is `tokio_total_local_schedule_count` from https://wufb-ds.tplant.com.au/metrics visualised in Grafana:

![image](https://github.com/static-web-server/static-web-server/assets/21111317/1013e78b-6685-4c6e-8a91-2d1c25a77a41)

2024-01-04 13:12 UTC, pl4nty commented
Not sure why FreeBSD CI is failing, [NetBSD is passing on GitHub Actions](https://github.com/pl4nty/static-web-server/actions/runs/7409900604/job/20161056204)

2024-01-04 14:15 UTC, pl4nty commented
For tests, I was thinking a simple `assert!(std::str::from_utf8(&body).unwrap().contains("tokio_workers_count"))` to start. I'm not sure how to implement tests with `RequestHandler` though. Do you have any guidance on how to mock it?

2024-01-05 21:18 UTC, joseluisq requested changes
Some minor changes to make for now. When those are done then I will suggest a few more.

2024-01-05 21:18 UTC, joseluisq commented on src/handler.rs
> +                let resp = Response::new(body);
Add the proper `Content-Type` for the Prometheus metrics response.

2024-01-05 21:18 UTC, joseluisq commented on src/handler.rs
> +    /// Metrics endpoint feature.
```suggestion
    /// Metrics endpoint feature (experimental).
```

2024-01-05 21:18 UTC, joseluisq commented on src/server.rs
> +        server_info!("experimental metrics endpoint: enabled={}", metrics);
```suggestion
        server_info!("metrics endpoint (experimental): enabled={}", metrics);
```

2024-01-05 21:18 UTC, joseluisq commented on src/server.rs
> +        // Metrics endpoint option
```suggestion
        // Metrics endpoint option (experimental)
```

2024-01-05 21:18 UTC, joseluisq commented on src/handler.rs
> +            if metrics_request {
Note that I moved `use prometheus::Encoder;` down here.

```suggestion
            #[cfg(linux)]
            if metrics_request {
                use prometheus::Encoder;

```

2024-01-05 21:18 UTC, joseluisq commented on src/server.rs
> +        }
```suggestion
        #[cfg(linux)]
        if metrics {
            prometheus::default_registry()
                .register(Box::new(
                    tokio_metrics_collector::default_runtime_collector(),
                ))
                .unwrap();
        }
```

2024-01-05 21:18 UTC, joseluisq commented on src/server.rs
> +                metrics,
```suggestion
                #[cfg(linux)]
                metrics,
```

2024-01-05 21:18 UTC, joseluisq commented on src/settings/cli.rs
> +    #[arg(
```suggestion
    #[cfg(linux)]
    #[arg(
```

2024-01-05 21:18 UTC, joseluisq commented on src/settings/mod.rs
> +        let mut metrics = opts.metrics;
```suggestion
        #[cfg(linux)]
        let mut metrics = opts.metrics;
```

2024-01-05 21:18 UTC, joseluisq commented on src/settings/mod.rs
> +                }
```suggestion
                #[cfg(linux)]
                if let Some(v) = general.metrics {
                    metrics = v
                }
```

2024-01-05 21:18 UTC, joseluisq commented on src/settings/mod.rs
> +                metrics,
```suggestion
                #[cfg(linux)]
                metrics,
```

2024-01-05 21:18 UTC, joseluisq commented on src/handler.rs
> +        let metrics_request =
```suggestion
        #[cfg(linux)]
        let metrics_request =
```

2024-01-05 21:18 UTC, joseluisq commented on src/handler.rs
>              if !method.is_allowed() {
When the changes above are done then move the whole "metrics endpoint check if block" to line 215. (before the CORS check)

2024-01-05 21:18 UTC, joseluisq commented on src/handler.rs
> +use prometheus::Encoder;
```suggestion
```

2024-01-05 21:18 UTC, joseluisq commented on src/settings/file.rs
> +    pub metrics: Option<bool>,
```suggestion
    /// Metrics endpoint feature (experimental).
    #[cfg(linux)]
    pub metrics: Option<bool>,
```

2024-01-05 21:30 UTC, joseluisq commented
> Not sure why FreeBSD CI is failing, [NetBSD is passing on GitHub Actions](https://github.com/pl4nty/static-web-server/actions/runs/7409900604/job/20161056204). Looks like I can disable it for just Windows and FreeBSD if needed

It looks like it can not be found most likely because it is not supported yet or something. Let's focus on Linux only.

> For tests, I was thinking a simple `assert!(std::str::from_utf8(&body).unwrap().contains("tokio_workers_count"))` to start. I'm not sure how to implement tests with `RequestHandler` though. Do you have any guidance on how to mock it?

You can use this test as a reference via a `tests/prometheus_metrics.rs` file. Also, you could add two tests one with the feature enabled and disabled.

https://github.com/static-web-server/static-web-server/blob/8815762f56fe7d499b50c4f598b5e90520c09e2e/tests/dir_listing.rs#L181-L222

2024-01-15 23:39 UTC, joseluisq commented
@pl4nty about testing, please forget my previous comment.
Recently, I published a testing utility and some test examples that you can use as a reference to test `RequestHandler`.

See https://github.com/static-web-server/static-web-server/pull/301/commits/76ab978c00899b8c51b8819b2505af62b5fecc30

2024-02-01 19:01 UTC, yonas commented
I can build on FreeBSD by passing `RUSTFLAGS="--cfg tokio_unstable"` to `cargo build --release`.

I'm not sure why it's not picking up this setting from `.cargo/config.toml` like the other distros.

2024-02-01 21:47 UTC, closed without merging

2024-02-01 22:04 UTC, joseluisq commented
For some strange reason, GH closed the PR (or I did it unintentionally) when I was force-pushing changes on top and now I can not reopen it.

@pl4nty I will simply create a new PR with your changes on top.

2024-02-01 22:17 UTC, joseluisq commented
Please let's continue the work on #307.