Fix the display format for file sizes
joseluisq/static-web-server pull request #376
Opened 2024-04-28 15:56 UTC by miroim

## Description

Replace `humansize` with a function `format_file_size` in `src/directory_listing.rs`
## Related Issue

https://github.com/static-web-server/static-web-server/issues/370

## How Has This Been Tested?

Add some test cases in `src/directory_listing.rs`
Compared and tested with local files

2024-04-28 16:50 UTC, palant requested changes
Looking good, and I do feel sorry about all the nitpicking.

2024-04-28 16:50 UTC, palant commented on src/directory_listing.rs
> +            return format!("{} {}", size_tmp, units[i]);
This case doesn’t need to be inside the loop – you can have bytes as a special case before it.

2024-04-28 16:50 UTC, palant commented on src/directory_listing.rs
> +    let units = ["B", "KiB", "MiB", "GiB", "TiB", "PiB"];
This should be a constant.

2024-04-28 16:50 UTC, palant commented on src/directory_listing.rs
> +    format!("{} {}", size_tmp, units[units.len() - 1])
We are going to have at most 4096 PiB in 64 bit, not large enough to strike the decimal points. So it’s probably best if we only iterate over `units[1 . .units.len() - 1]` – `units[0]` is handled as a special case up front and `units[units.len() - 1]` is a fallback unit to be used if the loop finishes without determining a suitable unit. You can really iterate over the values, not the indexes in that setup. And you’ll leave the loop with a value that you can divide by 1024.0 to display it.

2024-04-28 16:50 UTC, palant commented on src/directory_listing.rs
> +    use crate::directory_listing::format_file_size;
Nit: `use super::format_file_size;`

2024-04-28 16:50 UTC, palant commented on src/directory_listing.rs
> +        let size = 1690;
Nit: Maybe test 1024 just to see that trailing zeros aren’t removed?

2024-04-29 03:12 UTC, miroim commented
> Looking good, and I do feel sorry about all the nitpicking.

It's all part of helping me improve, and I appreciate your attention to detail.

2024-04-29 04:31 UTC, palant requested changes
Looks good, one tiny thing left to improve.

2024-04-29 04:31 UTC, palant commented on src/directory_listing.rs
> +        return format!("{} {}", size_tmp, "B");
Please use `UNITS[0]` as parameter here.

2024-04-29 05:57 UTC, palant approved these changes
LGTM

2024-04-29 06:50 UTC, joseluisq approved these changes
Thanks!

2024-04-29 06:51 UTC, merged

2024-04-29 20:27 UTC, palant commented
@miroim FYI, there was an issue with the code that clippy complained about (you have to run it with `--tests` command line flag). I fix it in #382.