DRAFT RFC Support inheriting TCP listener from parent process via fd0
joseluisq/static-web-server pull request #40
Opened 2021-05-13 20:56 UTC by tim-seoss

Hi,

Here's a rough draft PR.  Not for merging yet, just for possible discussion.

- I'm not really happy with the option parsing.  Having just a switch e.g. `static-web-server --inherit-listener` seems reasonable, but it doesn't look like you can do that and also have an ENV variable control the same thing.  I'll have a closer look at this.
- Probably better to split off the transition to a separated `bind` call into a separate commit.
- Not sure if the trace output is OK or not?
- Error handling should be improved.

Closes #36

2021-05-13 21:26 UTC, joseluisq commented
After a quick look there is some things like error handling to improve and minor refactorings to do but it's not so radical.
I will give it a second review soon after you fix first the linting issues since the CI complains.

2021-05-17 22:30 UTC, joseluisq commented
Any problem trying to fix those issues, how could I help?

BTW I would like to know the steps of how to test it.

2021-05-18 16:33 UTC, joseluisq commented
I have pushed a small commit to fix linting warnings.

2021-05-18 16:58 UTC, joseluisq reviewed
> Probably better to split off the transition to a separated bind call into a separate commit.

Yeah, that particular function can be improved a bit more. So feel free to suggest changes.

> Not sure if the trace output is OK or not?

It looks fine for me.

> Error handling should be improved.

Sure, panicking right now via `unwrap` or `expect` during startup is "fine". But let's improve it.
BTW the `start_server()` can return a `Result` which can help a bit here.

2021-05-18 16:58 UTC, joseluisq commented on src/config.rs
> +        conflicts_with_all(&["host", "port"])
> * I'm not really happy with the option parsing.  Having just a switch e.g. `static-web-server --inherit-listener` seems reasonable, but it doesn't look like you can do that and also have an ENV variable control the same thing.  I'll have a closer look at this.

Yeah the parsing sometimes is not obvious.
But it's easy to fix just append the `parse(try_from_str), default_value = "false"` to the `#[structopt(...` macro if you want to use boolean options with default values. Then you will be able to use just `-i`.

2021-05-18 17:06 UTC, joseluisq requested changes
One minor pending thing is the docs for the new arg option.
Right now we have a `README.md` file for that purpose under the `Environment Variables` and `Command-line arguments` sections. Probably you also want to introduce the feature under the `Features` section.

2021-05-18 17:13 UTC, joseluisq commented
> BTW I would like to know the steps of how to test it.

In general the PR looks fine however I would like to give it a test. I have a Linux so I could test it to verify functionality but I need you help here sharing a PR description with steps to do it so.

2021-05-18 17:59 UTC, tim-seoss commented
Sorry, work got busy this week.  I've done a chunk more work on it, but haven't tidied it up yet.  I'll try and get onto it later today or tomorrow.

2021-05-19 08:05 UTC, joseluisq commented
Don't worry take your time.
Just let you know that I have another PR almost ready to be merged today but it touches `src/server.rs` so  this PR can could have conflicts afterward. However is not really a problem I will send a minor commit here to keep it up-to-date if it's needed.

2021-05-19 08:19 UTC, joseluisq commented on src/config.rs
> +        conflicts_with_all(&["host", "port"])
Well, after a quick research turns out it is not possible via `structopt` (based on `clap` args parser). However looks like is doable just using `clap` directly but the downside is we need to redo `src/config.rs` from the scratch which is something that I don't think so happening now.

2021-05-21 08:53 UTC, tim-seoss commented
Still super-busy with work (I'm freelance so work can be a bit too "bursty" sometimes, when multiple clients all have simultaneous problems).  I will get back to this however.  Sorry for the delay...

2021-05-23 11:05 UTC, tim-seoss commented
Hopefully I'll have time later on today to rebase this...

2021-05-23 20:34 UTC, joseluisq approved these changes

2021-05-25 21:47 UTC, joseluisq approved these changes
Sorry for the delay.
Here my very simple test on Linux.

The sws service is launched just fine. I have used your example files and the server listening over TLS. Below the logs.
 
```sh
$ journalctl -xe
....
   Subject: Unit failed
   Defined-By: systemd
   Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
   
   The unit static-web-server.service has entered the 'failed' state with result 'exit-code'.
may 25 23:08:40 quintana systemd[1]: Stopped Static Web Server.
   Subject: A stop job for unit static-web-server.service has finished
   Defined-By: systemd
   Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
   
   A stop job for unit static-web-server.service has finished.
   
   The job identifier is 45055 and the job result is done.
may 25 23:08:40 quintana audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=static-web-server comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
may 25 23:08:40 quintana systemd[1]: static-web-server.service: Consumed 26.367s CPU time.
   Subject: Resources consumed by unit runtime
   Defined-By: systemd
   Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
   
   The unit static-web-server.service completed and consumed the indicated resources.
may 25 23:08:40 quintana kernel: audit: type=1131 audit(1621976920.880:5769): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=static-web-server comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
may 25 23:08:40 quintana polkitd[817]: Unregistered Authentication Agent for unix-process:19855:1382495 (system bus name :1.256, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale es_PE.UTF-8) (disconnected from bus)
may 25 23:08:40 quintana audit: BPF prog-id=1369 op=UNLOAD
may 25 23:08:40 quintana kernel: audit: type=1334 audit(1621976920.943:5770): prog-id=1369 op=UNLOAD
may 25 23:08:59 quintana audit[19904]: USER_AUTH pid=19904 uid=1001 auid=1001 ses=2 msg='op=PAM:authentication grantors=pam_faillock,pam_permit,pam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
may 25 23:08:59 quintana audit[19904]: USER_ACCT pid=19904 uid=1001 auid=1001 ses=2 msg='op=PAM:accounting grantors=pam_unix,pam_permit,pam_time acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
may 25 23:08:59 quintana sudo[19904]: joseluisq : TTY=pts/1 ; PWD=/etc/systemd/system ; USER=root ; COMMAND=/usr/bin/systemctl restart static-web-server.service
may 25 23:08:59 quintana audit[19904]: CRED_REFR pid=19904 uid=1001 auid=1001 ses=2 msg='op=PAM:setcred grantors=pam_faillock,pam_permit,pam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
may 25 23:08:59 quintana kernel: audit: type=1100 audit(1621976939.017:5771): pid=19904 uid=1001 auid=1001 ses=2 msg='op=PAM:authentication grantors=pam_faillock,pam_permit,pam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
may 25 23:08:59 quintana kernel: audit: type=1101 audit(1621976939.017:5772): pid=19904 uid=1001 auid=1001 ses=2 msg='op=PAM:accounting grantors=pam_unix,pam_permit,pam_time acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
may 25 23:08:59 quintana kernel: audit: type=1110 audit(1621976939.017:5773): pid=19904 uid=1001 auid=1001 ses=2 msg='op=PAM:setcred grantors=pam_faillock,pam_permit,pam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
may 25 23:08:59 quintana sudo[19904]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1001)
may 25 23:08:59 quintana audit[19904]: USER_START pid=19904 uid=1001 auid=1001 ses=2 msg='op=PAM:session_open grantors=pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
may 25 23:08:59 quintana kernel: audit: type=1105 audit(1621976939.020:5774): pid=19904 uid=1001 auid=1001 ses=2 msg='op=PAM:session_open grantors=pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
may 25 23:08:59 quintana systemd[1]: Listening on Static Web Server Socket.
   Subject: A start job for unit static-web-server.socket has finished successfully
   Defined-By: systemd
   Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
   
   A start job for unit static-web-server.socket has finished successfully.
   
   The job identifier is 45143.
may 25 23:08:59 quintana systemd[1]: Couldn't stat device /dev/urandom r: No such file or directory
may 25 23:08:59 quintana audit: BPF prog-id=1370 op=LOAD
may 25 23:08:59 quintana systemd[1]: Couldn't stat device /dev/random r: No such file or directory
may 25 23:08:59 quintana systemd[1]: Couldn't stat device /dev/null r: No such file or directory
may 25 23:08:59 quintana kernel: audit: type=1334 audit(1621976939.043:5775): prog-id=1370 op=LOAD
may 25 23:08:59 quintana systemd[1]: Started Static Web Server.
   Subject: A start job for unit static-web-server.service has finished successfully
   Defined-By: systemd
   Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
   
   A start job for unit static-web-server.service has finished successfully.
   
   The job identifier is 45056.
may 25 23:08:59 quintana audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=static-web-server comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
may 25 23:08:59 quintana kernel: audit: type=1130 audit(1621976939.047:5776): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=static-web-server comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
may 25 23:08:59 quintana audit[19904]: USER_END pid=19904 uid=1001 auid=1001 ses=2 msg='op=PAM:session_close grantors=pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
may 25 23:08:59 quintana audit[19904]: CRED_DISP pid=19904 uid=1001 auid=1001 ses=2 msg='op=PAM:setcred grantors=pam_faillock,pam_permit,pam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
may 25 23:08:59 quintana sudo[19904]: pam_unix(sudo:session): session closed for user root
may 25 23:08:59 quintana kernel: audit: type=1106 audit(1621976939.050:5777): pid=19904 uid=1001 auid=1001 ses=2 msg='op=PAM:session_close grantors=pam_limits,pam_unix,pam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
may 25 23:08:59 quintana kernel: audit: type=1104 audit(1621976939.050:5778): pid=19904 uid=1001 auid=1001 ses=2 msg='op=PAM:setcred grantors=pam_faillock,pam_permit,pam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/1 res=success'
may 25 23:10:16 quintana systemd[2400]: Started VTE child process 19966 launched by tilix process 2571.
   Subject: A start job for unit UNIT has finished successfully
   Defined-By: systemd
   Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
   
   A start job for unit UNIT has finished successfully.
   
   The job identifier is 614.
```

And here the security check via the command that you have suggested.

```sh
$ systemd-analyze security static-web-server.service
Overall exposure level for static-web-server.service: 0.6 SAFE 😀
```

Looks like everything is just working well.

The only thing that I have noted are the warnings in the journalctl logs above for `/dev/urandom` and others which seems related to `DeviceAllow` directive.
But since I have not really idea about it May you give please a small hint?

Anyway, no other observations to this respect from my limited knowledge.
If you want to suggest me other things to test just let me know. Otherwise if there are no objections from your side, then this PR is ready to be merged.

2021-05-25 21:50 UTC, joseluisq commented
Also the restart functionality that we have gained with this is also working fine. I crashed the server intentionally and then I got no service interruptions.

2021-05-26 09:19 UTC, joseluisq commented
I'm using my workstation with Arch Linux with latest systemd, no special configs.

2021-05-30 15:08 UTC, tim-seoss commented
Looks like the `DeviceAllow` lines I was using were invalid, but my testrig wasn't reporting that (not sure if due to a config difference, or systemd version difference).  I've pushed a fix for that.

2021-05-30 15:51 UTC, joseluisq commented
So warnings have disappeared.

```sh
$ journalctl -xe -u static-web-server
may 30 17:48:16 quintana systemd[1]: Stopped Static Web Server.
   Subject: A stop job for unit static-web-server.service has finished
   Defined-By: systemd
   Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
   
   A stop job for unit static-web-server.service has finished.
   
   The job identifier is 19263 and the job result is done.
may 30 17:48:42 quintana systemd[1]: Started Static Web Server.
   Subject: A start job for unit static-web-server.service has finished successfully
   Defined-By: systemd
   Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
   
   A start job for unit static-web-server.service has finished successfully.
   
   The job identifier is 19265.
```

Do you you want do something more or can we merge it?

2021-05-31 08:04 UTC, joseluisq approved these changes

2021-05-31 08:58 UTC, tim-seoss commented
I think it's pretty much there.  I'll just document the systemd unit file a bit more, and push those.  If you're happy with that further change, please go ahead!

Thanks!

Tim.

2021-05-31 09:15 UTC, tim-seoss commented
I've left that last change as a separate commit to make it easier to review.

LMK if you'd like me to squash it into the commit which added the systemd unit files (or feel free to do so yourself).

2021-05-31 10:14 UTC, joseluisq approved these changes
Good to know.
Everything looks fine.
I think you can help me squashing that commit then I can just merge it immediately.

2021-05-31 13:00 UTC, joseluisq approved these changes

2021-05-31 13:03 UTC, joseluisq commented
Definitely this is a great feature. I plan to deliver a new beta release (probably last beta pre major) this week. So I'll let you know when that happens.
Thanks for the effort!

2021-05-31 13:04 UTC, merged

2021-06-02 23:05 UTC, joseluisq commented
[v2.0.0-beta.4](https://github.com/joseluisq/static-web-server/releases/tag/v2.0.0-beta.4) released

2021-07-17 23:30 UTC, joseluisq commented
Just to let it know that this is no longer beta. See [v2.0.0](https://github.com/joseluisq/static-web-server/releases/tag/v2.0.0)