Truenas deprecated
joseluisq/static-web-server pull request #486
Opened 2024-09-29 15:41 UTC by ctag

Removes now deprecated installation instructions for Truenas/Truecharts.
https://truecharts.org/news/scale-deprecation/

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

2024-09-29 16:43 UTC, joseluisq commented
Thanks for the reminder. It seems like the Helm charts are still being maintained. https://github.com/truecharts/charts/tree/master/charts/stable/static-web-server

> **So, does this mean that TrueCharts is dead?**
> No, TrueCharts is not dead. We have always made Helm Charts and our Charts can be installed on any Helm-compatible OS, not just TrueNAS Scale. We continue to provide these Helm Charts as always and they can already be installed on a compatible OS.
> https://truecharts.org/news/scale-faq/

Maybe we have to make this clear in the docs instead of removing the entry?

2024-09-29 16:59 UTC, ctag commented
That's good at least, but helm charts aren't directly usable as Truenas installation material. Possibly just rename that section away from Truenas Scale.

2024-09-29 18:10 UTC, joseluisq commented
> For context, installing apps on Scale through the truecharts catalog is now fully broken. See: https://www.reddit.com/r/truenas/comments/1e1dxvk/truecharts_just_nuked_everything_in_response_to/
> So even though the helm charts are maintained, they aren't usable for Scale.

Fair, then let's remove any _TrueNAS Scale_ mention and adjust the section accordingly.

2024-10-01 11:15 UTC, joseluisq requested changes
I just left a minor adjustment to make.
After that, we should merge the PR.

2024-10-01 11:15 UTC, joseluisq commented on docs/content/features/docker.md
> -If you use Kubernetes with [TrueNAS SCALE](https://www.truenas.com/truenas-scale/) then check out the [TrueCharts Community Website](https://truecharts.org/charts/stable/static-web-server/) and its [
```suggestion
### TrueCharts
The [TrueCharts Community](https://truecharts.org) also provides a ready-to-use [Static Web Server Helm-Chart](https://truecharts.org/charts/stable/static-web-server/) that you can easily deploy in your Kubernetes.
```

2024-11-07 11:17 UTC, joseluisq approved these changes
Thanks!

2024-11-07 11:18 UTC, merged