Implement trusted_proxies
joseluisq/static-web-server pull request #495
Opened 2024-11-02 16:47 UTC by Jeidnx

## Description

Adds the trusted_proxies as a CLI and File option. It is entirely optional, meaning that existing uses of log_remote_address will silently stop logging from the forwarded-for header.

## Related Issue

#494 
## Motivation and Context

See #494 
## How Has This Been Tested?

I've done some manual testing with the cli and toml configuration, more to be done!
## Screenshots (if appropriate):

2024-11-02 16:53 UTC, Jeidnx commented on src/log_addr.rs
> +        let real_remote_addr =
This looks a bit convoluted to me. I considered creating a function something like this?
```rust
fn get_remote_addr(remote: Option<SocketAddrs>, trusted_proxies: Vec<IpAddr>) -> String
```

2024-11-03 10:15 UTC, joseluisq commented
It looks fine to me. You need to add some log examples in the PR description of your tests and update [the documentation page](https://static-web-server.net/features/logging/), you can find the doc page [here](https://github.com/static-web-server/static-web-server/blob/master/docs/content/features/logging.md) and check out [this](https://static-web-server.net/building-from-source/#building-documentation-from-source) if you want to build the docs locally.

Let me know when the PR is ready to review it.

--

Additionally, I wonder if we also need to support a _trust all proxies_ option for reverse proxies with non-static IPs like AWS ELB or similar.

2024-11-05 11:27 UTC, Jeidnx commented
Yeah i took some time to think it over and to me it seemed the most sensible thing was to seperate the x-forwarded-for logging from the remote address logging completely. I have introduced two new options, one to toggle logging of the x-forwarded-for header and one to optionally allowlist certain IPs, where the default is to trust all IPs.

I also ran into some issues when trying to build the docs, the command [here](https://static-web-server.net/building-from-source/#building-documentation-from-source) doesn't seem to mount the docs in the correct directory. I also found some other small issues with the documentation, i will open a seperate issue for this.

2024-11-05 11:52 UTC, joseluisq commented
> I also ran into some issues when trying to build the docs, the command [here](https://static-web-server.net/building-from-source/#building-documentation-from-source) doesn't seem to mount the docs in the correct directory. I also found some other small issues with the documentation, i will open a seperate issue for this.

The docs instructions are kind of outdated but feel free to update them.

For running the Docs dev server via Docker, just try `docker-compose -f docs/docker-compose.yml up --build`. This is what I use when testing changes across pages locally.

2024-11-07 13:43 UTC, Jeidnx commented
This is ready to be reviewed btw. Sorry i forgot to mention that.

2024-11-07 14:54 UTC, joseluisq commented
> This is ready to be reviewed btw. Sorry i forgot to mention that.

Great, I will give it a check today.

2024-11-08 01:01 UTC, joseluisq requested changes
It looks fine to me.
I just left an update on the logging feature page to do. After that, we should merge the PR.

2024-11-08 01:01 UTC, joseluisq commented on docs/content/configuration/command-line-arguments.md
> +          A comma separated list of IP addresses to accept the X-Forwarded-For header from. Empty means trust all IPs [env: SERVER_TRUSTED_PROXIES] [default: ""]
We also need to mention those two options in the [logging feature page](https://static-web-server.net/features/logging) with a couple of examples to explain the new feature.

2024-11-11 12:11 UTC, Jeidnx commented on docs/content/configuration/command-line-arguments.md
> +          A comma separated list of IP addresses to accept the X-Forwarded-For header from. Empty means trust all IPs [env: SERVER_TRUSTED_PROXIES] [default: ""]
Ah sorry i missed that. I have edited the page, but im not sure there are enough examples. On the other hand i think it already looks a bit cluttered. Please let me know what you think :)

2024-11-11 13:59 UTC, joseluisq approved these changes
Ready for the next release, Thanks!

2024-11-11 14:01 UTC, merged